In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.Series(np.random.randn(9),index=['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'])
data.index

Index(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], dtype='object')

In [6]:
data

a   -0.174767
a   -0.114575
a    0.820013
b   -1.354866
b   -0.360200
c   -0.990363
c   -0.981992
d   -0.093962
d    0.443904
dtype: float64

In [7]:
data1 = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1,2,3,1,3,1,2,2,3]])
data1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [9]:
data1

a  1   -1.148960
   2   -0.826461
   3    0.789299
b  1    0.545308
   3   -0.207185
c  1    0.733748
   2   -0.149006
d  2   -0.772600
   3    0.556717
dtype: float64

In [13]:
data1['a'][1]

np.float64(-1.1489601087862569)

In [14]:
data1.loc[:,2]

a   -0.826461
c   -0.149006
d   -0.772600
dtype: float64