In [1]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_movies.csv")
ratings = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_ratings.csv")

<ipython-input-3-056e10d78486>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/IMDb/IMDb_movies.csv")

In [4]:
movies.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN

In [6]:
ratings.head()

  imdb_title_id  weighted_average_vote  total_votes
0     tt0000009                    5.9          154
1     tt0000574                    6.1          589
2     tt0001892                    5.8          188
3     tt0002101                    5.2          446
4     tt0002130                    7.0         2237

In [8]:
pd.merge?

In [10]:
moveis_ratings = pd.merge(movies, ratings, on="imdb_title_id")
moveis_ratings.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget,weighted_average_vote,total_votes
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN,5.9,154
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250,6.1,589
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN,5.8,188
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000,5.2,446
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN,7.0,2237

In [11]:
moveis_ratings.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'budget',
       'weighted_average_vote', 'total_votes'],
      dtype='object')

In [13]:
extracted = moveis_ratings[['title', 'year', 'weighted_average_vote', 'total_votes']]
extracted

,title,year,weighted_average_vote,total_votes
0,Miss Jerry,1894,5.9,154
1,The Story of the Kelly Gang,1906,6.1,589
2,Den sorte drøm,1911,5.8,188
3,Cleopatra,1912,5.2,446
4,L'Inferno,1911,7.0,2237
...,...,...,...,...
85850,Le lion,2020,5.3,398
85851,De Beentjes van Sint-Hildegard,2020,7.7,724
85852,Padmavyuhathile Abhimanyu,2019,7.9,265
85853,Sokagin Çocuklari,2019,6.4,194
85854,La vida sense la Sara Amat,2019,6.7,102