In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/bank.csv", index_col=0, delimiter=";")
df

,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
age,,,,,,,,,,,,,,,,
30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [5]:
bank1, bank2, = df[2521:], df[:2521]

In [6]:
pd.concat([bank1,bank2])

,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
age,,,,,,,,,,,,,,,,
46,unemployed,married,secondary,no,3533,yes,no,cellular,12,aug,235,2,-1,0,unknown,no
59,blue-collar,divorced,secondary,no,3573,no,no,cellular,15,may,44,1,-1,0,unknown,no
44,management,divorced,tertiary,no,476,yes,yes,unknown,26,may,127,2,-1,0,unknown,no
35,blue-collar,married,secondary,no,1257,yes,no,cellular,20,apr,93,3,329,7,failure,no
55,blue-collar,married,unknown,no,23,no,no,cellular,30,jan,143,1,2,3,other,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,management,married,tertiary,no,1882,yes,no,cellular,11,aug,249,5,-1,0,unknown,no
48,blue-collar,married,unknown,no,131,yes,no,unknown,6,may,189,1,-1,0,unknown,no
30,technician,single,secondary,no,175,no,no,cellular,25,aug,167,4,-1,0,unknown,no
43,technician,single,tertiary,yes,0,no,no,cellular,29,aug,73,4,-1,0,unknown,no
38,management,divorced,tertiary,no,4425,yes,no,unknown,30,may,162,1,-1,0,unknown,no