In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
!wget "https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip"

--2025-04-15 17:06:58--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3037::6815:1e8d, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2025-04-15 17:06:58 (9.16 MB/s) - ‘chinook.zip’ saved [305596/305596]

In [3]:
!unzip "chinook.zip"

Archive:  chinook.zip
  inflating: chinook.db

In [4]:
db = sql.connect("chinook.db")
cursor = db.cursor()

In [7]:
cursor.execute('SELECT * FROM customers').fetchall()
command = 'SELECT * FROM customers'
df = pd.read_sql(command, db, index_col='CustomerId')
df.head()

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [8]:
command = 'SELECT * FROM customers ORDER BY LastName'
df = pd.read_sql(command, db, index_col='CustomerId')
df.head()

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
CustomerId,,,,,,,,,,,,
12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3

In [10]:
query = 'SELECT DISTINCT Country FROM customers'
df = pd.read_sql(query, db)
df

           Country
0           Brazil
1          Germany
2           Canada
3           Norway
4   Czech Republic
5          Austria
6          Belgium
7          Denmark
8              USA
9         Portugal
10          France
11         Finland
12         Hungary
13         Ireland
14           Italy
15     Netherlands
16          Poland
17           Spain
18          Sweden
19  United Kingdom
20       Australia
21       Argentina
22           Chile
23           India