In [1]:
import pandas as pd
import sqlite3 as sql

In [5]:
db = sql.connect("new.db")
cursor = db.cursor()

In [6]:
df = pd.read_csv("drive/MyDrive/datasets/Electricity_Production_By_Source.csv")
df

,Entity,Code,Year,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [7]:
cols = ['country', 'code', 'year', 'coal', 'gas', 'hydro', 'renewable_other', 'solar', 'oil', 'wind', 'nuclear']
df.columns = cols
df

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [8]:
df.to_sql("electricity", db)

6241

In [14]:
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
cursor.fetchall()

[('electricity',)]

In [15]:
cursor.execute('PRAGMA table_info(electricity)')
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [16]:
cursor.execute('SELECT * FROM electricity WHERE country = "Uzbekistan"').fetchall()

[(5964,
  'Uzbekistan',
  'UZB',
  2000,
  11.6024052568697,
  25.5234513739546,
  5.817,
  0.0,
  0.0,
  1.38014336917562,
  0.0,
  0.0),
 (5965,
  'Uzbekistan',
  'UZB',
  2001,
  11.7663201911589,
  25.8840382317801,
  5.899,
  0.0,
  0.0,
  1.39964157706093,
  0.0,
  0.0),
 (5966,
  'Uzbekistan',
  'UZB',
  2002,
  12.214374432497,
  26.8696864994026,
  6.124,
  0.0,
  0.0,
  1.45293906810035,
  0.0,
  0.0),
 (5967,
  'Uzbekistan',
  'UZB',
  2003,
  11.8335132616487,
  26.0318523297491,
  7.544,
  0.0,
  0.0,
  1.40763440860215,
  0.0,
  0.0),
 (5968,
  'Uzbekistan',
  'UZB',
  2004,
  11.595776344086,
  25.5088688172043,
  8.92,
  0.0,
  0.0,
  1.37935483870967,
  0.0,
  0.0),
 (5969,
  'Uzbekistan',
  'UZB',
  2005,
  11.4909189964157,
  25.2781992831541,
  8.838,
  0.0,
  0.0,
  1.3668817204301,
  0.0,
  0.0),
 (5970,
  'Uzbekistan',
  'UZB',
  2006,
  11.8277882915173,
  26.0192583034647,
  4.653,
  0.0,
  0.0,
  1.40695340501792,
  0.0,
  0.0),
 (5971,
  'Uzbekistan',
  'UZB',
  2007,
  12.0516647550776,
  26.5117510155316,
  4.61,
  0.0,
  0.0,
  1.43358422939068,
  0.0,
  0.0),
 (5972,
  'Uzbekistan',
  'UZB',
  2008,
  10.7742732616487,
  23.7016923297491,
  4.443,
  0.0,
  0.0,
  1.28163440860215,
  0.0,
  0.0),
 (5973,
  'Uzbekistan',
  'UZB',
  2009,
  9.08462467924528,
  28.0175300377358,
  6.418,
  0.0,
  0.0,
  1.08064528301886,
  0.0,
  0.0),
 (5974,
  'Uzbekistan',
  'UZB',
  2010,
  9.79202664528301,
  30.199200335849,
  8.11,
  0.0,
  0.0,
  1.16479301886792,
  0.0,
  0.0),
 (5975,
  'Uzbekistan',
  'UZB',
  2011,
  10.5340942150943,
  32.487781445283,
  5.646,
  0.0,
  0.0,
  1.25306433962264,
  0.0,
  0.0),
 (5976,
  'Uzbekistan',
  'UZB',
  2012,
  10.3650155283018,
  31.9663325849056,
  6.586,
  0.0,
  0.0,
  1.23295188679245,
  0.0,
  0.0),
 (5977,
  'Uzbekistan',
  'UZB',
  2013,
  10.9393463056603,
  33.7376033169811,
  5.647,
  0.0,
  0.001996,
  1.30127037735849,
  0.0,
  0.0),
 (5978,
  'Uzbekistan',
  'UZB',
  2014,
  11.1126743245283,
  34.2721573735849,
  6.014,
  0.0,
  0.002046,
  1.32188830188679,
  0.0,
  0.0),
 (5979,
  'Uzbekistan',
  'UZB',
  2015,
  10.519788522807,
  35.780628845614,
  6.998,
  0.0,
  0.002176,
  1.25136263157894,
  0.0,
  0.0),
 (5980,
  'Uzbekistan',
  'UZB',
  2016,
  10.7838905929824,
  36.6789109859649,
  7.254,
  0.0,
  0.004643,
  1.28277842105263,
  0.0,
  0.0),
 (5981,
  'Uzbekistan',
  'UZB',
  2017,
  10.9987074736842,
  37.4095609473684,
  8.343,
  0.0,
  0.00629,
  1.30833157894736,
  0.0,
  0.0),
 (5982,
  'Uzbekistan',
  'UZB',
  2018,
  11.853192045614,
  40.315892691228,
  5.83803,
  0.0,
  0.006827,
  1.40997526315789,
  0.0,
  0.0),
 (5983,
  'Uzbekistan',
  'UZB',
  2019,
  12.2976598865497,
  41.8276473064327,
  5.45137333333333,
  0.0,
  0.006827,
  1.46284614035087,
  0.0,
  0.0),
 (5984,
  'Uzbekistan',
  'UZB',
  1985,
  None,
  None,
  5.4314426,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5985,
  'Uzbekistan',
  'UZB',
  1986,
  None,
  None,
  4.618273,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5986,
  'Uzbekistan',
  'UZB',
  1987,
  None,
  None,
  6.7705208,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5987,
  'Uzbekistan',
  'UZB',
  1988,
  None,
  None,
  7.1638474,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5988,
  'Uzbekistan',
  'UZB',
  1989,
  None,
  None,
  5.502153,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5989,
  'Uzbekistan',
  'UZB',
  1990,
  None,
  None,
  6.648,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5990,
  'Uzbekistan',
  'UZB',
  1991,
  None,
  None,
  6.031000000000001,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5991,
  'Uzbekistan',
  'UZB',
  1992,
  None,
  None,
  6.281000000000001,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5992,
  'Uzbekistan',
  'UZB',
  1993,
  None,
  None,
  7.358,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5993,
  'Uzbekistan',
  'UZB',
  1994,
  None,
  None,
  7.156000000000001,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5994,
  'Uzbekistan',
  'UZB',
  1995,
  None,
  None,
  6.188,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5995,
  'Uzbekistan',
  'UZB',
  1996,
  None,
  None,
  6.525,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5996,
  'Uzbekistan',
  'UZB',
  1997,
  None,
  None,
  5.777,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5997,
  'Uzbekistan',
  'UZB',
  1998,
  None,
  None,
  5.757999999999999,
  0.0,
  0.0,
  None,
  0.0,
  0.0),
 (5998,
  'Uzbekistan',
  'UZB',
  1999,
  None,
  None,
  5.692,
  0.0,
  0.0,
  None,
  0.0,
  0.0)]