In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
db = sql.connect("new.db")
cursor = db.cursor()

In [3]:
df = pd.read_csv("drive/MyDrive/datasets/Electricity_Production_By_Source.csv")
df.columns = ['country', 'code', 'year', 'coal', 'gas', 'hydro', 'renewable_other', 'solar', 'oil', 'wind', 'nuclear']
df.head(3)

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0

In [4]:
df.to_sql("electricity", db)

6241

In [8]:
query = """
CREATE TABLE IF NOT EXISTS worldpop (
  rank INT,
  country TEXT PRIMARY KEY,
  density REAL,
  population DOUBLE NOT NULL,
  area INT NOT NULL
);
"""
cursor.execute(query)
db.commit()

In [6]:
cursor.execute('SELECT name FROM sqlite_master WHERE type = "table"').fetchall()

[('electricity',), ('worldpop',)]

In [7]:
cursor.execute('PRAGMA table_info(electricity)').fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [9]:
query = "INSERT INTO worldpop VALUES(1, 'Macaoe', 21946.4667, 658.3940, 30)"
cursor.execute(query)
db.commit()

In [10]:
cursor.execute('SELECT * FROM worldpop').fetchall()

[(1, 'Macaoe', 21946.4667, 658.394, 30)]

In [12]:
query = "INSERT INTO worldpop (country, population, area) VALUES('Uzbekistan', 33935.7630, 447400)"
cursor.execute(query)
db.commit()

In [13]:
cursor.execute('SELECT * FROM worldpop').fetchall()

[(1, 'Macaoe', 21946.4667, 658.394, 30),
 (None, 'Uzbekistan', None, 33935.763, 447400)]

In [14]:
pd.read_sql('SELECT * FROM worldpop', db)

   rank     country     density  population    area
0   1.0      Macaoe  21946.4667     658.394      30
1   NaN  Uzbekistan         NaN   33935.763  447400