In [1]:
import pandas as pd
import sqlite3 as sql

In [9]:
!wget "https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db"

--2025-04-16 09:45:47--  https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db [following]
--2025-04-16 09:45:47--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 565248 (552K) [application/octet-stream]
Saving to: ‘electricity.db’

electricity.db      100%[===================>] 552.00K  --.-KB/s    in 0.1s

2025-04-16 09:45:48 (5.29 MB/s) - ‘electricity.db’ saved [565248/565248]

In [10]:
db = sql.connect('electricity.db')
cursor = db.cursor()

In [11]:
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"').fetchall()

[('elect',)]

In [13]:
pd.read_sql('SELECT * FROM elect', db)

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6236,6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [14]:
query = 'SELECT DISTINCT country FROM elect'
pd.read_sql(query, db)

            country
0       Afghanistan
1            Africa
2           Albania
3           Algeria
4    American Samoa
..              ...
230  Western Sahara
231           World
232           Yemen
233          Zambia
234        Zimbabwe

[235 rows x 1 columns]

In [15]:
'Uzbekistan' in pd.read_sql(query, db)['country'].values

True

In [17]:
dfuz = pd.read_sql('SELECT year, coal, gas, hydro FROM elect WHERE country="Uzbekistan"', db)
dfuz

    year       coal        gas     hydro
0   2000  11.602405  25.523451  5.817000
1   2001  11.766320  25.884038  5.899000
2   2002  12.214374  26.869686  6.124000
3   2003  11.833513  26.031852  7.544000
4   2004  11.595776  25.508869  8.920000
5   2005  11.490919  25.278199  8.838000
6   2006  11.827788  26.019258  4.653000
7   2007  12.051665  26.511751  4.610000
8   2008  10.774273  23.701692  4.443000
9   2009   9.084625  28.017530  6.418000
10  2010   9.792027  30.199200  8.110000
11  2011  10.534094  32.487781  5.646000
12  2012  10.365016  31.966333  6.586000
13  2013  10.939346  33.737603  5.647000
14  2014  11.112674  34.272157  6.014000
15  2015  10.519789  35.780629  6.998000
16  2016  10.783891  36.678911  7.254000
17  2017  10.998707  37.409561  8.343000
18  2018  11.853192  40.315893  5.838030
19  2019  12.297660  41.827647  5.451373
20  1985        NaN        NaN  5.431443
21  1986        NaN        NaN  4.618273
22  1987        NaN        NaN  6.770521
23  1988        NaN        NaN  7.163847
24  1989        NaN        NaN  5.502153
25  1990        NaN        NaN  6.648000
26  1991        NaN        NaN  6.031000
27  1992        NaN        NaN  6.281000
28  1993        NaN        NaN  7.358000
29  1994        NaN        NaN  7.156000
30  1995        NaN        NaN  6.188000
31  1996        NaN        NaN  6.525000
32  1997        NaN        NaN  5.777000
33  1998        NaN        NaN  5.758000
34  1999        NaN        NaN  5.692000