In [5]:
import pandas as pd
import numpy as np

In [3]:
!wget = "https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/merc.csv"

--2025-04-12 06:10:49--  http://=/
Resolving = (=)... failed: Name or service not known.
wget: unable to resolve host address ‘=’
--2025-04-12 06:10:49--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/merc.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 728047 (711K) [text/plain]
Saving to: ‘merc.csv.1’

merc.csv.1          100%[===================>] 710.98K  --.-KB/s    in 0.06s

2025-04-12 06:10:49 (12.2 MB/s) - ‘merc.csv.1’ saved [728047/728047]

FINISHED --2025-04-12 06:10:49--
Total wall clock time: 0.1s
Downloaded: 1 files, 711K in 0.06s (12.2 MB/s)

In [2]:
!git clone "https://github.com/anvarnarz/praktikum_datasets"

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 44 (delta 43), pack-reused 93 (from 1)
Receiving objects: 100% (145/145), 9.72 MiB | 15.24 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [7]:
df = pd.read_csv('sample_data/california_housing_test.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [8]:
df = pd.read_csv('praktikum_datasets/merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [10]:
df = pd.read_excel('praktikum_datasets/uzbekistan.xlsx', index_col=0, names=['Hudud', 'Maydon', 'Aholi'])
df.head()

                   Maydon    Aholi
Hudud
Andijon viloyati     4200  1899000
Buxoro viloyati     39400  1384700
Fargʻona viloyati    6800  2597000
Jizzax viloyati     20500   910500
Xorazm viloyati      6300  1200000

In [16]:
pd.read_csv('praktikum_datasets/automobile_data.csv', sep=",", index_col='index', nrows=15)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970
13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760
14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315
15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880
16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151
17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295