In [2]:
import pandas as pd
import numpy as np

In [1]:
!git clone "https://github.com/anvarnarz/praktikum_datasets"

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 44 (delta 43), pack-reused 93 (from 1)
Receiving objects: 100% (145/145), 9.72 MiB | 11.21 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [4]:
df = pd.read_excel('praktikum_datasets/uzbekistan.xlsx')
df.head()

          Boʻlinishi  Maydoni (kv.km)  Aholisi
0   Andijon viloyati             4200  1899000
1    Buxoro viloyati            39400  1384700
2  Fargʻona viloyati             6800  2597000
3    Jizzax viloyati            20500   910500
4    Xorazm viloyati             6300  1200000

In [5]:
df2 = pd.read_csv('praktikum_datasets/automobile_data.csv')
df2.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [3]:
hdfobj = pd.HDFStore('data.h5')

In [6]:
hdfobj.put('uz_data', df)

In [7]:
hdfobj.put('auto_data', df2)

In [8]:
hdfobj.keys()

['/auto_data', '/uz_data']

In [9]:
hdfobj['uz_data'].head()

          Boʻlinishi  Maydoni (kv.km)  Aholisi
0   Andijon viloyati             4200  1899000
1    Buxoro viloyati            39400  1384700
2  Fargʻona viloyati             6800  2597000
3    Jizzax viloyati            20500   910500
4    Xorazm viloyati             6300  1200000

In [10]:
hdfobj.close()

In [11]:
hdfobj['uz_data'].head()

ClosedFileError: data.h5 file is not open!

In [14]:
hdfobj = pd.HDFStore('data.h5')

In [16]:
hdfobj.close()

In [18]:
data = pd.read_hdf('data.h5', key='uz_data')

ValueError: The file 'data.h5' is already opened, but not in read-only mode (as requested).

In [19]:
data.to_hdf('data.h5', key='uz_data')

NameError: name 'data' is not defined