In [1]:
import pandas as pd
import numpy as np

In [ ]:
!git clone "https://github.com/anvarnarz/praktikum_datasets"

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 44 (delta 43), pack-reused 93 (from 1)
Receiving objects: 100% (145/145), 9.72 MiB | 11.21 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [7]:
data = pd.read_html("https://en.wikipedia.org/wiki/Tashkent")
len(data)

18

In [8]:
data[0].head()

,Tashkent Toshkent / Тошкент,Tashkent Toshkent / Тошкент.1
0,Capital city,Capital city
1,Tashkent,Tashkent
2,Skyline of Tashkent with Nest OneSupreme Assem...,Skyline of Tashkent with Nest OneSupreme Assem...
3,FlagSeal,FlagSeal
4,Nickname(s): Tosh (lit. 'The rock'),Nickname(s): Tosh (lit. 'The rock')

In [9]:
data[5]

   Climate data for Tashkent (1991–2020, extremes 1867–present)  \
                                                          Month
0                                 Record high °C (°F)
1                          Mean daily maximum °C (°F)
2                                  Daily mean °C (°F)
3                          Mean daily minimum °C (°F)
4                                  Record low °C (°F)
5                   Average precipitation mm (inches)
6              Average extreme snow depth cm (inches)
7                                  Average rainy days
8                                  Average snowy days
9                       Average relative humidity (%)
10                        Mean monthly sunshine hours
11                        Source 1: Pogoda.ru.net[54]
12                                 Source 2: NOAA[55]

                                                              \
                            Jan                          Feb
0                   22.6 (72.7)                  27.0 (80.6)
1                    7.2 (45.0)                   9.5 (49.1)
2                    2.3 (36.1)                   4.2 (39.6)
3                   −1.3 (29.7)                   0.1 (32.2)
4                     −28 (−18)                −25.6 (−14.1)
5                   54.9 (2.16)                  72.1 (2.84)
6                       3 (1.2)                      2 (0.8)
7                            14                           13
8                             9                            7
9                            73                           68
10                        104.7                        119.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Mar                          Apr
0                   32.5 (90.5)                  36.4 (97.5)
1                   16.0 (60.8)                  22.3 (72.1)
2                   10.2 (50.4)                  15.9 (60.6)
3                    5.3 (41.5)                  10.1 (50.2)
4                   −16.9 (1.6)                  −6.3 (20.7)
5                   66.4 (2.61)                  63.3 (2.49)
6                         0 (0)                        0 (0)
7                            14                           12
8                             2                            0
9                            61                           60
10                        169.2                        222.7
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            May                          Jun
0                  39.9 (103.8)                 43.0 (109.4)
1                   28.0 (82.4)                  33.6 (92.5)
2                   21.1 (70.0)                  26.2 (79.2)
3                   14.3 (57.7)                  18.4 (65.1)
4                   −1.7 (28.9)                   3.8 (38.8)
5                   41.1 (1.62)                  16.8 (0.66)
6                         0 (0)                        0 (0)
7                            11                            7
8                             0                            0
9                            53                           40
10                        303.0                        352.8
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Jul                          Aug
0                  44.6 (112.3)                 43.1 (109.6)
1                   35.9 (96.6)                  34.9 (94.8)
2                   28.3 (82.9)                  26.6 (79.9)
3                   20.1 (68.2)                  18.4 (65.1)
4                    8.2 (46.8)                   5.7 (42.3)
5                    3.4 (0.13)                   2.1 (0.08)
6                         0 (0)                        0 (0)
7                             4                            3
8                             0                            0
9                            39                           42
10                        386.5                        353.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Sep                          Oct
0                  40.0 (104.0)                  37.5 (99.5)
1                   29.5 (85.1)                  22.2 (72.0)
2                   21.0 (69.8)                  14.4 (57.9)
3                   13.4 (56.1)                   8.3 (46.9)
4                    0.1 (32.2)                 −11.2 (11.8)
5                    4.6 (0.18)                  23.7 (0.93)
6                         0 (0)                        0 (0)
7                             3                            7
8                             0                            1
9                            45                           57
10                        283.8                        220.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Nov                          Dec
0                   31.6 (88.9)                  27.3 (81.1)
1                   14.1 (57.4)                   8.6 (47.5)
2                    8.1 (46.6)                   3.5 (38.3)
3                    3.6 (38.5)                  −0.1 (31.8)
4                  −22.1 (−7.8)                −29.5 (−21.1)
5                   51.2 (2.02)                  58.4 (2.30)
6                         0 (0)                      2 (0.8)
7                            10                           12
8                             2                            6
9                            66                           73
10                        135.0                        104.7
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]


                           Year
0                  44.6 (112.3)
1                   21.8 (71.3)
2                   15.2 (59.3)
3                    9.2 (48.6)
4                 −29.5 (−21.1)
5                 458.0 (18.03)
6                       3 (1.2)
7                           110
8                            27
9                            56
10                       2755.6
11  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]