In [2]:
import pandas as pd
import numpy as np

In [4]:
!git clone "https://github.com/anvarnarz/praktikum_datasets"

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 145 (delta 46), reused 44 (delta 43), pack-reused 93 (from 1)
Receiving objects: 100% (145/145), 9.72 MiB | 13.40 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [7]:
!wget -O universities_ranking.json "https://storage.googleapis.com/kagglesdsdata/datasets/996631/1682217/universities_ranking.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250414%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250414T090900Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=91b9c580078a1b83c5ddb4c729038675c368c81cf290de9042a80516eaa183435ce95a6838e118140d63bd0ad1c74addef25a8660b6e7b687946c459c75fcbc1f3ba3514243fab7b4574d16677cc3f653fd9dd574895c4072b88fcda4520788d8207d52169c6a845bd615992a745bc99faf974a21a8d590e9a401768369da4af1f6f220deaae9d4757b549666ed490fd26f8b40d7c5f02b0585d1dd237883a31bff69070c857d6795d418aa4774e694515e81bdc1b33587631769a77608a6f83760e0b2b7823ca5a22c400c773c2de29f9ea6f9ae23d6fafbe91ea91b65a86e412fc91dbad26fae5a3e64d0f04999d57a94489601f25f24da9afbbd9a7f9ea12"

--2025-04-14 09:28:26--  https://storage.googleapis.com/kagglesdsdata/datasets/996631/1682217/universities_ranking.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250414%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250414T090900Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=91b9c580078a1b83c5ddb4c729038675c368c81cf290de9042a80516eaa183435ce95a6838e118140d63bd0ad1c74addef25a8660b6e7b687946c459c75fcbc1f3ba3514243fab7b4574d16677cc3f653fd9dd574895c4072b88fcda4520788d8207d52169c6a845bd615992a745bc99faf974a21a8d590e9a401768369da4af1f6f220deaae9d4757b549666ed490fd26f8b40d7c5f02b0585d1dd237883a31bff69070c857d6795d418aa4774e694515e81bdc1b33587631769a77608a6f83760e0b2b7823ca5a22c400c773c2de29f9ea6f9ae23d6fafbe91ea91b65a86e412fc91dbad26fae5a3e64d0f04999d57a94489601f25f24da9afbbd9a7f9ea12
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.141.207, 74.125.137.207, 142.250.101.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.141.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 393811 (385K) [application/json]
Saving to: ‘universities_ranking.json’

universities_rankin 100%[===================>] 384.58K  1.34MB/s    in 0.3s

2025-04-14 09:28:27 (1.34 MB/s) - ‘universities_ranking.json’ saved [393811/393811]

In [8]:
pd.read_json("universities_ranking.json")

,ranking,title,location,number students,students staff ratio,perc intl students,gender ratio
0,1,University of Oxford,United Kingdom,"20,774",11.1,41%,46 : 54
1,2,Stanford University,United States,"16,223",7.4,23%,44 : 56
2,3,Harvard University,United States,"21,261",9.3,25%,49 : 51
3,4,California Institute of Technology,United States,"2,238",6.3,33%,36 : 64
4,5,Massachusetts Institute of Technology,United States,"11,276",8.4,34%,39 : 61
...,...,...,...,...,...,...,...
1521,1522,Yuan Ze University,Taiwan,"8,188",19.7,7%,42 : 58
1522,1523,Yuriy Fedkovych Chernivtsi National University,Ukraine,"12,616",10.7,0%,57 : 43
1523,1524,Zagazig University,Egypt,"156,270",24.4,2%,54 : 46
1524,1525,University of Zagreb,Croatia,"59,336",15.3,3%,59 : 41
1525,1526,University of Žilina,Slovakia,"7,136",11.7,2%,34 : 66

In [10]:
import requests
r = requests.get("https://openlibrary.org/subjects/python.json?published_in=2010-2025")
r.status_code

200

In [11]:
r.json()

{'key': '/subjects/python',
 'name': 'python',
 'subject_type': 'subject',
 'work_count': 114,
 'works': [{'key': '/works/OL2784125W',
   'title': 'Learning Python',
   'edition_count': 22,
   'cover_id': 1312568,
   'cover_edition_key': 'OL9497269M',
   'subject': ['Python (Langage de programmation)',
    'Python (linguagem de programação)',
    'Python (Computer program language)',
    'Python (Lenguaje de programación de computadores)',
    'Langage à objets',
    'Python (programmeertaal)',
    'Object-oriented programming (Computer science)',
    'Python (Computer language)',
    'Interpréteur',
    'Python',
    'COMPUTERS',
    'Programming Languages',
    'Engineering & Applied Sciences',
    'Computer Science',
    'General',
    'Reference',
    'Games',
    'Com051360',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.prog_lang',
    'Professional, career & trade -> computer science -> programming languages (jr/sr)',
    'Professional, career & trade -> computer science -> general',
    'Professional, career & trade -> computer science -> python'],
   'ia_collection': ['americana',
    'inlibrary',
    'internetarchivebooks',
    'printdisabled',
    'schroederlibrary-ol'],
   'printdisabled': True,
   'lending_edition': 'OL37873566M',
   'lending_identifier': 'einfuhrunginpyth0000lutz',
   'authors': [{'key': '/authors/OL411267A', 'name': 'Mark Lutz'},
    {'key': '/authors/OL2726848A', 'name': 'David Ascher'}],
   'first_publish_year': 1999,
   'ia': 'einfuhrunginpyth0000lutz',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_unavailable',
    'available_to_browse': False,
    'available_to_borrow': False,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'einfuhrunginpyth0000lutz',
    'isbn': '9783897211292',
    'oclc': None,
    'openlibrary_work': 'OL27741348W',
    'openlibrary_edition': 'OL37873566M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': True,
    'is_browseable': False,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL2784127W',
   'title': 'Python',
   'edition_count': 13,
   'cover_id': 988215,
   'cover_edition_key': 'OL8942751M',
   'subject': ['Python (Computer program language)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'Games',
    'Com051360',
    'Cs.cmp_sc.prog_lang'],
   'ia_collection': ['americana',
    'binghamton-ol',
    'inlibrary',
    'internetarchivebooks',
    'printdisabled',
    'the-claremont-colleges-ol'],
   'printdisabled': True,
   'lending_edition': 'OL24453347M',
   'lending_identifier': 'pythonpocketrefe00lutz_1',
   'authors': [{'key': '/authors/OL411267A', 'name': 'Mark Lutz'}],
   'first_publish_year': 1998,
   'ia': 'pythonpocketrefe00lutz_1',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': True,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'pythonpocketrefe00lutz_1',
    'isbn': '9780596158088',
    'oclc': None,
    'openlibrary_work': 'OL15489566W',
    'openlibrary_edition': 'OL24453347M',
    'last_loan_date': '2020-07-04T23:18:02Z',
    'num_waitlist': '0',
    'last_waitlist_date': '2019-10-16T21:09:00Z',
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL16976951W',
   'title': 'Think Python',
   'edition_count': 11,
   'cover_id': 7363360,
   'cover_edition_key': 'OL25763659M',
   'subject': ['Computer programming',
    'Software architecture',
    'Python (Computer program language)',
    'COMPUTERS / Programming Languages / C#',
    'COMPUTERS / Programming Languages / Pascal',
    'COMPUTERS / Programming Languages / Java',
    'Computer',
    'Programming Languages',
    'General',
    'Python',
    'Bioinformatics',
    'Games',
    'Com051360',
    'Cs.cmp_sc.prog_lang'],
   'ia_collection': ['additional_collections',
    'folkscanomy',
    'folkscanomy_computer',
    'folkscanomy_computer_inbox',
    'inlibrary',
    'internetarchivebooks',
    'printdisabled'],
   'printdisabled': True,
   'lending_edition': 'OL26455778M',
   'lending_identifier': '2015ThinkPython',
   'authors': [{'key': '/authors/OL6815485A', 'name': 'Allen B. Downey'},
    {'key': '/authors/OL12493148A', 'name': 'Allen Downey'}],
   'first_publish_year': 2009,
   'ia': '2015ThinkPython',
   'public_scan': True,
   'has_fulltext': True,
   'availability': {'status': 'open',
    'available_to_browse': False,
    'available_to_borrow': False,
    'available_to_waitlist': False,
    'is_printdisabled': False,
    'is_readable': True,
    'is_lendable': False,
    'is_previewable': True,
    'identifier': '2015ThinkPython',
    'isbn': None,
    'oclc': None,
    'openlibrary_work': 'OL16976951W',
    'openlibrary_edition': 'OL26455778M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': False,
    'is_browseable': False,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL17795703W',
   'title': 'Python for bioinformatics',
   'edition_count': 10,
   'cover_id': 8078288,
   'cover_edition_key': 'OL26385029M',
   'subject': ['Bioinformatics',
    'Python (computer program language)',
    'Python (Computer program language)',
    'Computational Biology',
    'Bio-informatique',
    'Python (Langage de programmation)',
    'Programming languages (Electronic computers)',
    'Programming Languages',
    'Langages de programmation',
    'COMPUTERS',
    'Python',
    'NATURE',
    'Reference',
    'SCIENCE',
    'Life Sciences',
    'Biology',
    'General'],
   'ia_collection': [''],
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL3871440A', 'name': 'Sebastian Bassi'}],
   'first_publish_year': 2009,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL21349037W',
   'title': 'Introduction to Python for Science and Engineering',
   'edition_count': 10,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Python (computer program language)',
    'Engineering, data processing',
    'Science, data processing',
    'Python (Computer program language)',
    'Computer programming',
    'Engineering',
    'Data processing',
    'Science',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'General',
    'MATHEMATICS',
    'SCIENCE',
    'Physics'],
   'ia_collection': [''],
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL4194836A', 'name': 'David J. Pine'}],
   'first_publish_year': 2018,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False},
  {'key': '/works/OL2784126W',
   'title': 'Programming Python',
   'edition_count': 10,
   'cover_id': 805644,
   'cover_edition_key': 'OL8667192M',
   'subject': ['Python (Computer program language)',
    'Qa76.73.p98 l88 2001',
    'Qa 76.73 p98 l875 2001',
    'Python',
    'Object oriented',
    'General',
    'Games',
    'Com051360',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.prog_lang',
    'Python (programmeertaal)'],
   'ia_collection': ['americanuniversity-ol',
    'inlibrary',
    'internetarchivebooks',
    'printdisabled',
    'riceuniversity-ol',
    'rochester-ol',
    'unb-ol',
    'uni-ol',
    'wilsoncollege-ol'],
   'printdisabled': True,
   'lending_edition': 'OL3969544M',
   'lending_identifier': 'programmingpytho00lutz',
   'authors': [{'key': '/authors/OL411267A', 'name': 'Mark Lutz'}],
   'first_publish_year': 1996,
   'ia': 'programmingpytho00lutz',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': True,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'programmingpytho00lutz',
    'isbn': '9780596000851',
    'oclc': None,
    'openlibrary_work': 'OL2784131W',
    'openlibrary_edition': 'OL3969544M',
    'last_loan_date': '2020-09-08T08:38:01Z',
    'num_waitlist': '0',
    'last_waitlist_date': '2020-02-28T21:21:40Z',
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL15667639W',
   'title': 'Mining the Social Web',
   'edition_count': 9,
   'cover_id': 9721114,
   'cover_edition_key': 'OL24598391M',
   'subject': ['Social networking',
    'Online social networks',
    'Artificial intelligence',
    'Data mining',
    'Electronic data processing, distributed processing',
    'General',
    'Page design',
    'Com060140',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.intrn_www',
    'Cs.offc_tch.intrn_wb_pg_dsg',
    'Professional, career & trade -> computer science -> internet & www',
    'Professional, career & trade -> computer science -> general',
    'Web programming',
    'Python'],
   'ia_collection': ['inlibrary', 'internetarchivebooks', 'printdisabled'],
   'printdisabled': True,
   'lending_edition': 'OL26838560M',
   'lending_identifier': 'miningsocialwebd0000russ',
   'authors': [{'key': '/authors/OL6887918A', 'name': 'Matthew A. Russell'}],
   'first_publish_year': 2011,
   'ia': 'miningsocialwebd0000russ',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': False,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'miningsocialwebd0000russ',
    'isbn': '9781449367619',
    'oclc': None,
    'openlibrary_work': 'OL19547994W',
    'openlibrary_edition': 'OL26838560M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL15664278W',
   'title': 'Head First Python',
   'edition_count': 9,
   'cover_id': 6681113,
   'cover_edition_key': 'OL24596470M',
   'subject': ['Programming languages (electronic computers)',
    'Python (Computer program language)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'C♯',
    'Java',
    'Pascal',
    'Scripting languages (Computer science)',
    'Computers and IT',
    'Python',
    'General',
    'Games',
    'Com051360',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.prog_lang'],
   'ia_collection': ['inlibrary',
    'internetarchivebooks',
    'popularchinesebooks',
    'printdisabled'],
   'printdisabled': True,
   'lending_edition': 'OL35343633M',
   'lending_identifier': 'headfirstpythonz0000paul',
   'authors': [{'key': '/authors/OL6867889A', 'name': 'Paul Barry'}],
   'first_publish_year': 2010,
   'ia': 'headfirstpythonz0000paul',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': False,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'headfirstpythonz0000paul',
    'isbn': '9787512322233',
    'oclc': None,
    'openlibrary_work': 'OL15664278W',
    'openlibrary_edition': 'OL35343633M',
    'last_loan_date': None,
    'num_waitlist': None,
    'last_waitlist_date': None,
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL6045694W',
   'title': 'Python in a Nutshell',
   'edition_count': 8,
   'cover_id': 389166,
   'cover_edition_key': 'OL7581267M',
   'subject': ['Python (Computer program language)',
    'Python (programmeertaal)',
    'Scripting languages (Computer science)',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': ['americanuniversity-ol',
    'drakeuniversity-ol',
    'inlibrary',
    'internetarchivebooks',
    'johnshopkins-ol',
    'printdisabled',
    'wilsoncollege-ol'],
   'printdisabled': True,
   'lending_edition': 'OL24749091M',
   'lending_identifier': 'pythoninnutshell00mart',
   'authors': [{'key': '/authors/OL1521655A', 'name': 'Alex Martelli'},
    {'key': '/authors/OL2726934A', 'name': 'Anna Ravenscroft'},
    {'key': '/authors/OL2804309A', 'name': 'Steve Holden'}],
   'first_publish_year': 2002,
   'ia': 'pythoninnutshell00mart',
   'public_scan': False,
   'has_fulltext': True,
   'availability': {'status': 'borrow_available',
    'available_to_browse': True,
    'available_to_borrow': True,
    'available_to_waitlist': False,
    'is_printdisabled': True,
    'is_readable': False,
    'is_lendable': True,
    'is_previewable': True,
    'identifier': 'pythoninnutshell00mart',
    'isbn': '0596001886',
    'oclc': None,
    'openlibrary_work': 'OL15839297W',
    'openlibrary_edition': 'OL3703974M',
    'last_loan_date': '2020-08-17T04:02:58Z',
    'num_waitlist': '0',
    'last_waitlist_date': '2019-10-16T21:09:11Z',
    'is_restricted': True,
    'is_browseable': True,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL17422847W',
   'title': 'Python For Data Analysis',
   'edition_count': 8,
   'cover_id': 7548132,
   'cover_edition_key': None,
   'subject': ['Programming languages (Electronic computers)',
    'Python (Computer program language)',
    'Data mining',
    'Python (Langage de programmation)',
    'Exploration de données (Informatique)',
    'COMPUTERS',
    'Programming Languages',
    'Python',
    'Python 3.6',
    'Datenanalyse',
    'Datenmanagement',
    'Data processing',
    'General',
    'Games',
    'Com051360',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.prog_lang',
    'Qa76.73.p98 m35 2017',
    '005.13/3'],
   'ia_collection': [''],
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL7309633A', 'name': 'Wes McKinney'}],
   'first_publish_year': 2012,
   'ia': 'pythonfordataana00mcki',
   'public_scan': False,
   'has_fulltext': False,
   'availability': {'status': 'error',
    'error_message': 'not found',
    'identifier': 'pythonfordataana00mcki',
    'is_restricted': True,
    'is_browseable': False,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL16223034W',
   'title': 'Think Stats',
   'edition_count': 8,
   'cover_id': 6956191,
   'cover_edition_key': 'OL25083068M',
   'subject': ['Statistics',
    'Study and teaching',
    'Computer programs',
    'MATHEMATICS / Probability & Statistics / General',
    'Statistics / Computer programs',
    'Statistics / Study and teaching',
    'Probabilities',
    'Statistics, data processing',
    'Programmed instruction',
    'Quantitative research',
    'Statistics, study and teaching',
    'Data modeling & design',
    'General',
    'Python',
    'Forecasting',
    'Econometrics',
    'Office automation',
    'Com062000',
    'Cs.decis_scs.bus_fcst',
    'Cs.ecn.forec_econo',
    'Cs.offc_tch.simul_prjct'],
   'ia_collection': [''],
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL6815485A', 'name': 'Allen B. Downey'}],
   'first_publish_year': 2011,
   'ia': 'thinkstats00down_338',
   'public_scan': True,
   'has_fulltext': True,
   'availability': {'status': 'error',
    'error_message': 'not found',
    'identifier': 'thinkstats00down_338',
    'is_restricted': True,
    'is_browseable': False,
    '__src__': 'core.models.lending.get_availability'}},
  {'key': '/works/OL23330617W',
   'title': 'Making music with computers',
   'edition_count': 7,
   'cover_id': None,
   'cover_edition_key': None,
   'subject': ['Computer composition',
    'Python (Computer program language)',
    'COMPUTERS / Programming Languages / General',
    'COMPUTERS / Programming / Algorithms',
    'MATHEMATICS / General',
    'Python (computer program language)',
    'Computer software',
    'Development',
    'Python (Langage de programmation)',
    'COMPUTERS',
    'Programming Languages',
    'Python'],
   'ia_collection': [''],
   'printdisabled': False,
   'lending_edition': '',
   'lending_identifier': '',
   'authors': [{'key': '/authors/OL3853673A', 'name': 'Bill Manaris'}],
   'first_publish_year': 2013,
   'ia': None,
   'public_scan': False,
   'has_fulltext': False}]}

In [13]:
pd.DataFrame(r.json()['works'])

,key,title,edition_count,cover_id,cover_edition_key,subject,ia_collection,printdisabled,lending_edition,lending_identifier,authors,first_publish_year,ia,public_scan,has_fulltext,availability
0,/works/OL2784125W,Learning Python,22,1312568.0,OL9497269M,"[Python (Langage de programmation), Python (li...","[americana, inlibrary, internetarchivebooks, p...",True,OL37873566M,einfuhrunginpyth0000lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1999,einfuhrunginpyth0000lutz,False,True,"{'status': 'borrow_unavailable', 'available_to..."
1,/works/OL2784127W,Python,13,988215.0,OL8942751M,"[Python (Computer program language), Python (L...","[americana, binghamton-ol, inlibrary, internet...",True,OL24453347M,pythonpocketrefe00lutz_1,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1998,pythonpocketrefe00lutz_1,False,True,"{'status': 'borrow_available', 'available_to_b..."
2,/works/OL16976951W,Think Python,11,7363360.0,OL25763659M,"[Computer programming, Software architecture, ...","[additional_collections, folkscanomy, folkscan...",True,OL26455778M,2015ThinkPython,"[{'key': '/authors/OL6815485A', 'name': 'Allen...",2009,2015ThinkPython,True,True,"{'status': 'open', 'available_to_browse': Fals..."
3,/works/OL17795703W,Python for bioinformatics,10,8078288.0,OL26385029M,"[Bioinformatics, Python (computer program lang...",[],False,,,"[{'key': '/authors/OL3871440A', 'name': 'Sebas...",2009,None,False,False,NaN
4,/works/OL21349037W,Introduction to Python for Science and Enginee...,10,NaN,None,"[Python (computer program language), Engineeri...",[],False,,,"[{'key': '/authors/OL4194836A', 'name': 'David...",2018,None,False,False,NaN
5,/works/OL2784126W,Programming Python,10,805644.0,OL8667192M,"[Python (Computer program language), Qa76.73.p...","[americanuniversity-ol, inlibrary, internetarc...",True,OL3969544M,programmingpytho00lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1996,programmingpytho00lutz,False,True,"{'status': 'borrow_available', 'available_to_b..."
6,/works/OL15667639W,Mining the Social Web,9,9721114.0,OL24598391M,"[Social networking, Online social networks, Ar...","[inlibrary, internetarchivebooks, printdisabled]",True,OL26838560M,miningsocialwebd0000russ,"[{'key': '/authors/OL6887918A', 'name': 'Matth...",2011,miningsocialwebd0000russ,False,True,"{'status': 'borrow_available', 'available_to_b..."
7,/works/OL15664278W,Head First Python,9,6681113.0,OL24596470M,"[Programming languages (electronic computers),...","[inlibrary, internetarchivebooks, popularchine...",True,OL35343633M,headfirstpythonz0000paul,"[{'key': '/authors/OL6867889A', 'name': 'Paul ...",2010,headfirstpythonz0000paul,False,True,"{'status': 'borrow_available', 'available_to_b..."
8,/works/OL6045694W,Python in a Nutshell,8,389166.0,OL7581267M,"[Python (Computer program language), Python (p...","[americanuniversity-ol, drakeuniversity-ol, in...",True,OL24749091M,pythoninnutshell00mart,"[{'key': '/authors/OL1521655A', 'name': 'Alex ...",2002,pythoninnutshell00mart,False,True,"{'status': 'borrow_available', 'available_to_b..."
9,/works/OL17422847W,Python For Data Analysis,8,7548132.0,None,"[Programming languages (Electronic computers),...",[],False,,,"[{'key': '/authors/OL7309633A', 'name': 'Wes M...",2012,pythonfordataana00mcki,False,False,"{'status': 'error', 'error_message': 'not foun..."
10,/works/OL16223034W,Think Stats,8,6956191.0,OL25083068M,"[Statistics, Study and teaching, Computer prog...",[],False,,,"[{'key': '/authors/OL6815485A', 'name': 'Allen...",2011,thinkstats00down_338,True,True,"{'status': 'error', 'error_message': 'not foun..."
11,/works/OL23330617W,Making music with computers,7,NaN,None,"[Computer composition, Python (Computer progra...",[],False,,,"[{'key': '/authors/OL3853673A', 'name': 'Bill ...",2013,None,False,False,NaN