In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv',index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [9]:
df['rating'] = df['year'].rank()
df.sort_values('rating',ascending=True)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left,1.0
405,25,ford,door,1984,salvage insurance,41577,white,2ftcf15y9eca14589,167611661,arkansas,usa,17 hours left,2.0
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left,3.0
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,4.5
362,25,ford,pickup,1994,salvage insurance,206162,white,1ftdf15y2rnb12612,167361489,georgia,usa,2 days left,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,23400,ford,fusion,2020,clean vehicle,2452,gray,3fa6p0hd6lr110753,167749593,michigan,usa,21 hours left,2475.5
1642,20600,ford,fusion,2020,clean vehicle,17858,black,3fa6p0cd8lr115427,167570001,virginia,usa,2 days left,2475.5
206,25,chevrolet,vehicl,2020,salvage insurance,7232,black,2gnaxkev6l6128374,167756877,kentucky,usa,3 days left,2475.5
1640,27000,ford,mustang,2020,clean vehicle,12748,red,1fatp8uh3l5101487,167569997,virginia,usa,2 days left,2475.5
1638,20000,ford,fusion,2020,clean vehicle,23984,silver,3fa6p0cd0lr116667,167569992,virginia,usa,2 days left,2475.5

In [11]:
df['rating'] = df['price'].rank(method='max')
df.sort_values('rating',ascending=False)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left,2499.0
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left,2498.0
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left,2497.0
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left,2496.0
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left,2495.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,0,chevrolet,door,2009,salvage insurance,117059,black,kl1td66e39b645208,167418694,colorado,usa,18 hours left,43.0
305,0,ford,door,2003,salvage insurance,246065,gold,1fafp55u03a242094,167610324,kansas,usa,8 days left,43.0
510,0,ford,door,2010,salvage insurance,86841,silver,3fahp0ga3ar366961,167357806,oklahoma,usa,17 hours left,43.0
522,0,ford,door,2008,salvage insurance,145483,red,1fmcu03128kc80487,167357813,oklahoma,usa,17 hours left,43.0
144,0,dodge,door,2014,salvage insurance,123660,silver,1c3cdzab0en111068,167756167,utah,usa,2 days left,43.0