In [2]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [11]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/uzbekistan.csv',index_col=0)
df.sample(3)

                               Maydoni (kv.km)    Aholisi
Boʻlinishi
Qoraqalpogʻiston Respublikasi         160000.0  1200000.0
Fargʻona viloyati                       6800.0  2597000.0
Surxondaryo viloyati                   20800.0  1676000.0

In [12]:
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/gm_sales.csv',index_col=0)
df2.sample(3)

         2020   2021
Cobalt  44901  36317
Damas   30889  33682
Labo     4521   7542

In [13]:
df2.sum()

2020    168712
2021    124734
dtype: int64

In [14]:
df2.sum(axis=1)

Labo      12063
Damas     64571
Spark     22855
Nexia     56105
Cobalt    81218
Gentra    56634
dtype: int64