In [1]:
import pandas as pd
from pandas import Series
import numpy as np

In [2]:
cars_dict = {
    "Malibu" : 45000,
    "Onix" : 20000,
    "Cobalt": 10000,
    "Gentra": 15000,
    "Damas": 8000
}
car_series = Series(cars_dict)
car_series

Malibu    45000
Onix      20000
Cobalt    10000
Gentra    15000
Damas      8000
dtype: int64

In [3]:
"Malibu" in car_series

True

In [4]:
"Spark" in car_series

False

In [5]:
car_series['Onix']

np.int64(20000)

In [6]:
models = ["Malibu", "Onix", "Cobalt", "Lacetti", "Gentra", "Damas"]
models

['Malibu', 'Onix', 'Cobalt', 'Lacetti', 'Gentra', 'Damas']

In [7]:
cars2 = Series(cars_dict, index=models)
cars2

Malibu     45000.0
Onix       20000.0
Cobalt     10000.0
Lacetti        NaN
Gentra     15000.0
Damas       8000.0
dtype: float64