In [15]:
import pandas as pd
from pandas import DataFrame

In [16]:
usernames = {"anvar": "anvarbek223", "olim": "olimtoy", "maryam":"maryam334455", "javohir":"javohir445"}
emails = {"anvar": "anvar@gmail.com", "olim":"olim@mail.ru", "maryam": "mary33@gmail.com", "javohir": "javohir445@gmail.com"}
data ={
    'username': usernames,
    'email': emails
}
df = DataFrame(data)
df

             username                 email
anvar     anvarbek223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com

In [17]:
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [18]:
arr = ['anvar', 'olim', 'maryam', 'javohir']
arr[0]

'anvar'

In [19]:
arr[1]

'olim'

In [23]:
data2 = {
    'username':{'olim':'olimjon','maryam':'maryam2020'},
    'email':{'olim':'olimjon2021@mail.ru', 'maryam':'maryam20@gmail.com'}
}
df2 = pd.concat([df, pd.DataFrame(data2)])
df2

             username                 email
anvar     anvarbek223       anvar@gmail.com
olim          olimtoy          olim@mail.ru
maryam   maryam334455      mary33@gmail.com
javohir    javohir445  javohir445@gmail.com
olim          olimjon   olimjon2021@mail.ru
maryam     maryam2020    maryam20@gmail.com

In [30]:
newid = pd.Index(['olim', 'husan', 'hasan'])
newid

Index(['olim', 'husan', 'hasan'], dtype='object')

In [32]:
newid.isin(df2.index)

array([ True, False, False])

In [36]:
newid.difference(df.index)

Index(['hasan', 'husan'], dtype='object')

In [38]:
df2.index.union(newid)

Index(['anvar', 'hasan', 'husan', 'javohir', 'maryam', 'maryam', 'olim',
       'olim'],
      dtype='object')

In [40]:
df2.index.delete(0)

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [41]:
newid.drop('husan')

Index(['olim', 'hasan'], dtype='object')

In [42]:
df2.index.insert(0, 'husan')

Index(['husan', 'anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [45]:
df2.index.is_unique

False

In [47]:
df2.index.unique()

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')