In [3]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/MOCK_USER_DATA.csv", index_col=0)
df

    first_name   last_name                           email       gender   age
id
1      Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2      Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3       Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4         Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5     Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48
..         ...         ...                             ...          ...   ...
96        Baxy       Marcu        bmarcu2n@list-manage.com      Agender    64
97      Kattie     Claxson          kclaxson2o@booking.com       Female    18
98        Clem     Fullerd  cfullerd2p@creativecommons.org     Bigender    55
99   Desdemona     Jurasek        djurasek2q@aboutads.info  Genderfluid    46
100      Mable     Toffano          mtoffano2r@myspace.com     Bigender   233

[100 rows x 5 columns]

In [12]:
len(df)

100

In [13]:
randlist = np.random.permutation(len(df))
randlist

array([93,  7, 97, 78, 18, 23, 60, 54, 80, 83, 37, 87, 56,  3,  4, 22, 43,
       67, 17, 99, 34, 58, 62, 28, 51, 57, 48, 65, 16, 88, 91, 90, 82, 77,
       44, 55, 49, 42, 40, 64, 31, 75, 79, 21, 38, 63, 27, 19, 68, 12, 94,
       24, 39, 46, 86, 98, 41, 70, 85, 25, 13, 10,  8, 92, 59, 95,  9, 26,
       15, 96, 29, 52, 72, 61, 47, 33, 45, 74,  5, 11,  1, 69, 32, 35,  6,
       76, 30, 50,  2, 53, 84, 20, 81, 66, 73, 14, 71,  0, 36, 89])

In [14]:
df.index = randlist
df

   first_name   last_name                           email       gender   age
93    Dorothy     Verryan               dverryan0@who.int   Non-binary     1
7     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
97     Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
78       Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
18   Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48
..        ...         ...                             ...          ...   ...
14       Baxy       Marcu        bmarcu2n@list-manage.com      Agender    64
71     Kattie     Claxson          kclaxson2o@booking.com       Female    18
0        Clem     Fullerd  cfullerd2p@creativecommons.org     Bigender    55
36  Desdemona     Jurasek        djurasek2q@aboutads.info  Genderfluid    46
89      Mable     Toffano          mtoffano2r@myspace.com     Bigender   233

[100 rows x 5 columns]