In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/earthquake-database/database.csv

In [ ]:
df = pd.read_csv('/kaggle/input/earthquake-database/database.csv')
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [ ]:
df = df.dropna()
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
565,12/20/1966,15:30:01,37.302167,-116.408333,Nuclear Explosion,1.20,31.61,16.0,5.62,ML,...,10.0,261.00,1.476000,99.000,0.8600,CI3329931,CI,CI,CI,Reviewed
897,04/26/1968,15:00:02,37.295333,-116.455667,Nuclear Explosion,1.20,31.61,17.0,5.63,ML,...,6.0,261.00,1.438000,99.000,1.0300,CI3342128,CI,CI,CI,Reviewed
1129,12/19/1968,16:30:01,37.231500,-116.473667,Nuclear Explosion,1.40,31.61,16.0,5.52,ML,...,6.0,257.00,1.415000,99.000,1.3600,CI3342181,CI,CI,CI,Reviewed
1380,09/16/1969,14:30:01,37.314167,-116.460667,Nuclear Explosion,1.20,31.61,13.0,5.82,ML,...,8.0,268.00,1.437000,99.000,0.3300,CI3326197,CI,CI,CI,Reviewed
1532,03/26/1970,19:00:01,37.300500,-116.534167,Nuclear Explosion,1.20,31.61,16.0,5.54,ML,...,10.0,260.00,1.377000,99.000,0.3500,CI3325031,CI,CI,CI,Reviewed
2723,06/06/1973,13:00:01,37.245000,-116.346000,Nuclear Explosion,1.10,31.61,17.0,5.64,ML,...,8.0,259.00,1.517000,99.000,0.5500,CI3319623,CI,CI,CI,Reviewed
3307,11/22/1974,16:25:34,30.250000,-114.800000,Earthquake,6.00,31.61,20.0,5.55,ML,...,4.0,312.00,2.641000,99.000,3.2200,CI3319062,CI,CI,CI,Reviewed
3516,06/26/1975,12:30:01,37.278833,-116.368667,Nuclear Explosion,6.00,31.61,19.0,5.52,ML,...,13.0,260.00,1.504000,99.000,3.4400,CI12328563,CI,CI,CI,Reviewed
3673,10/28/1975,14:30:00,37.290167,-116.411500,Nuclear Explosion,1.30,31.61,19.0,5.67,ML,...,8.0,260.00,1.472000,99.000,2.7500,CI3006257,CI,CI,CI,Reviewed
3754,01/03/1976,19:15:01,37.296500,-116.333167,Nuclear Explosion,1.50,31.61,20.0,5.84,ML,...,8.0,261.00,1.534000,99.000,0.4400,CI3001652,CI,CI,CI,Reviewed
5523,05/18/1980,15:32:11,46.207333,-122.188000,Earthquake,1.51,0.56,18.0,5.70,MD,...,1.0,62.00,0.008296,0.682,0.2200,UW10084803,UW,UW,UW,Reviewed
5631,09/07/1980,04:36:38,38.138333,-118.391333,Earthquake,6.00,31.61,5.0,5.52,ML,...,12.0,333.00,1.090000,8.020,0.3300,CI9735242,CI,CI,CI,Reviewed
18876,02/21/2008,14:16:03,41.144400,-114.872100,Earthquake,7.90,1.90,18.0,6.20,ML,...,4.0,95.21,0.318000,1.610,0.1855,NN00234425,NN,NN,NN,Reviewed
22238,05/28/2014,21:15:07,18.045000,-68.350900,Earthquake,90.00,2.00,31.0,5.80,ML,...,12.0,262.80,0.467124,2.900,0.4100,PR14148004,PR,PR,PR,Reviewed

In [ ]:
import datetime as dt

In [ ]:
hozir = dt.datetime.now()
type(hozir)

datetime.datetime

In [ ]:
print(hozir)

2025-04-19 08:20:15.081075

In [ ]:
hozir.hour

8

In [ ]:
hozir.weekday()

5

In [ ]:
hozir.month

4

In [ ]:
hozir.minute

20