In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/earthquake-database/database.csv

In [21]:
df = pd.read_csv('/kaggle/input/earthquake-database/database.csv')
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [22]:
df = df.fillna(0)
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,0.0,0.0,6.0,MW,...,0.0,0.00,0.000,0.0,0.0000,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,0.0,0.0,5.8,MW,...,0.0,0.00,0.000,0.0,0.0000,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,0.0,0.0,6.2,MW,...,0.0,0.00,0.000,0.0,0.0000,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,0.0,0.0,5.8,MW,...,0.0,0.00,0.000,0.0,0.0000,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,0.0,0.0,5.8,MW,...,0.0,0.00,0.000,0.0,0.0000,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,0.0,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,0.0,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,0.0,5.9,MWW,...,0.0,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,0.0,6.3,MWW,...,0.0,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,0.0,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [23]:
import datetime as dt

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 23412 non-null  float64
 7   Depth Seismic Stations      23412 non-null  float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23412 non-null  object
 10  Magnitude Error             23412 non-null  float64
 11  Magnitude Seismic Stations  23412 non-null  float64
 12  Azimuthal Gap               23412 non-null  float64
 13  Horizontal Distance         23412 non-null  float64
 14  Horizontal Error            23412 non-null  float64
 15  Root Mean Square            23412 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [42]:
df['datetime'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,0.0,0.0,6.0,MW,...,0.0,0.0,0.0,0.0,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-02
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,0.0,0.0,5.8,MW,...,0.0,0.0,0.0,0.0,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-04
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,0.0,0.0,6.2,MW,...,0.0,0.0,0.0,0.0,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-05
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,0.0,0.0,5.8,MW,...,0.0,0.0,0.0,0.0,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-08
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,0.0,0.0,5.8,MW,...,0.0,0.0,0.0,0.0,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-09

In [44]:
df.at[0,'datetime'].weekday()

5

In [46]:
df['month'] = df['datetime'].dt.month

In [47]:
df['month'].value_counts()

month
3     2114
8     2014
12    2001
11    1987
9     1985
4     1971
5     1964
10    1952
1     1891
7     1880
2     1829
6     1824
Name: count, dtype: int64

In [48]:
df['weekday'] = df['datetime'].dt.weekday
df['weekday'].value_counts()

weekday
5    3433
2    3431
4    3362
0    3349
3    3306
6    3287
1    3244
Name: count, dtype: int64

In [50]:
df['time'] = pd.to_datetime(df['Time'], format="%H:%M:%S")
df.head()

ValueError: time data "1975-02-23T02:58:41.000Z" doesn't match format "%H:%M:%S", at position 3378. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [52]:
df['Time'].str.len().value_counts()

Time
8     23409
24        3
Name: count, dtype: int64

In [53]:
df[df['Time'].str.len()==24]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,month,weekday
3378,02/23/1975,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,0.0,0.0,5.6,MB,...,0.0,0.00,USP0000A09,US,US,US,Reviewed,1975-02-23,2,6
7512,04/28/1985,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,0.0,0.0,5.6,MW,...,0.0,1.30,USP0002E81,US,US,HRV,Reviewed,1985-04-28,4,6
20650,03/13/2011,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,0.0,1.06,USP000HWQP,US,US,GCMT,Reviewed,2011-03-13,3,6

In [54]:
df.loc[3378, 'Time'] = "02:58:41"
df.loc[7512, 'Time'] = "02:53:41"
df.loc[20650, 'Time'] = "02:23:34"

In [55]:
df[df['Time'].str.len()==24]

Empty DataFrame
Columns: [Date, Time, Latitude, Longitude, Type, Depth, Depth Error, Depth Seismic Stations, Magnitude, Magnitude Type, Magnitude Error, Magnitude Seismic Stations, Azimuthal Gap, Horizontal Distance, Horizontal Error, Root Mean Square, ID, Source, Location Source, Magnitude Source, Status, datetime, month, weekday]
Index: []

[0 rows x 24 columns]

In [67]:
df['time'] = pd.to_datetime(df['Time'], format="%H:%M:%S")
df.sample()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,month,weekday,time
19579,07/29/2009,14:52:08,22.572,143.263,Earthquake,140.1,0.0,239.0,5.5,MWC,...,0.82,USP000GZSP,US,US,GCMT,Reviewed,2009-07-29,7,2,1900-01-01 14:52:08

In [68]:
df['time'].dt.hour.value_counts()

time
13    1058
18    1029
3     1029
10    1017
7     1005
17     998
6      998
5      996
19     996
11     981
14     981
8      978
2      977
4      975
23     966
1      954
0      948
12     946
21     945
20     939
9      930
15     926
22     923
16     917
Name: count, dtype: int64

In [69]:
df['time'].dt.minute.value_counts()

time
11    435
59    435
15    425
6     420
16    419
8     418
1     413
32    412
3     408
19    408
5     406
26    406
0     404
4     404
42    404
53    403
41    402
51    402
56    401
23    399
9     399
46    396
39    396
27    396
40    395
22    394
43    394
2     394
33    392
17    392
24    391
36    391
31    390
37    390
35    389
12    386
58    386
18    385
57    384
30    384
48    383
10    383
45    383
49    382
13    379
20    379
25    376
14    375
55    371
54    368
50    368
38    368
21    365
47    365
34    362
52    361
29    357
44    356
28    343
7     340
Name: count, dtype: int64

In [77]:
df[(df['time'].dt.hour==13)&(df['time'].dt.minute==11)&(df['datetime'].dt.weekday==6)&(df['datetime'].dt.month==3)].shape

(1, 25)