In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv", index_col=1)
df

,index,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
company,,,,,,,,,
alfa-romero,0,convertible,88.6,168.8,dohc,four,111,21,13495.0
alfa-romero,1,convertible,88.6,168.8,dohc,four,111,21,16500.0
alfa-romero,2,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
audi,3,sedan,99.8,176.6,ohc,four,102,24,13950.0
audi,4,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
volkswagen,81,sedan,97.3,171.7,ohc,four,85,27,7975.0
volkswagen,82,sedan,97.3,171.7,ohc,four,52,37,7995.0
volkswagen,86,sedan,97.3,171.7,ohc,four,100,26,9995.0
volvo,87,sedan,104.3,188.8,ohc,four,114,23,12940.0
volvo,88,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [6]:
df.index.unique()

Index(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda', 'isuzu',
       'jaguar', 'mazda', 'mercedes-benz', 'mitsubishi', 'nissan', 'porsche',
       'toyota', 'volkswagen', 'volvo'],
      dtype='object', name='company')

In [7]:
df.groupby("company").mean(numeric_only=True)

,index,wheel-base,length,horsepower,average-mileage,price
company,,,,,,
alfa-romero,1.00,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,4.50,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,12.00,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,17.00,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,19.50,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,28.00,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,31.00,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,34.00,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,38.60,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,45.50,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,50.50,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,55.00,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,62.00,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,70.00,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,82.25,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,87.50,104.300000,188.800000,114.000000,23.000000,13177.500000

In [ ]:
df.groupby(['company']).agg(
    max_price=('price', 'max'),
    min_price=('price', 'min')
)

                 price
company
alfa-romero    13495.0
audi           13950.0
bmw            16430.0
chevrolet       5151.0
dodge           6229.0
honda           7295.0
isuzu           6785.0
jaguar         32250.0
mazda           5195.0
mercedes-benz  25552.0
mitsubishi      5389.0
nissan          6649.0
porsche        34028.0
toyota          5348.0
volkswagen      7775.0
volvo          12940.0